services:
  planteller-web:
    image: caddy:2.8-alpine
    container_name: planteller-web
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    environment:
      - EMAIL=${EMAIL}
    volumes:
      - ../:/srv/site:ro
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy_data:/data
      - caddy_config:/config

volumes:
  caddy_data:
  caddy_config:
